# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:

jobs:
  build:
  
    

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        ls
        bash clone_or_pull_all_repos.sh
        python -B src/dashboard.py
        |
        env:
          F8A_API_URL_STAGE: http://bayesian-api-bayesian-preview.b6ff.rh-idev.openshiftapps.com
          F8A_API_URL_PROD= https://recommender.api.openshift.io
          F8A_JOB_API_URL_STAGE: http://bayesian-jobs-bayesian-preview.b6ff.rh-idev.openshiftapps.com
          F8A_JOB_API_URL_PROD: http://bayesian-jobs-bayesian-production.09b5.dsaas.openshiftapps.com
          RECOMMENDER_API_TOKEN_STAGE: ""
          RECOMMENDER_API_TOKEN_PROD: ""
          JOB_API_TOKEN_STAGE: ""
          JOB_API_TOKEN_PROD: ""
          AWS_ACCESS_KEY_ID: ""
          AWS_SECRET_ACCESS_KEY: ""
          S3_REGION_NAME: "us-east-1"

    
